---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:
  - name: Generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  # Disable until dependencies properly updated
  #- name: audit
  #  image: node:12
  #  commands:
  #    - npm audit --package-lock-only --audit-level=moderate --production

  - name: Install
    image: node:12
    commands:
      - npm ci
    environment:
      # Cannot be true because of node-sass
      NPM_CONFIG_IGNORE_SCRIPTS: false

  - name: Test
    image: node:12
    commands:
      - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: Build
    image: node:12
    commands:
      - npm run build

  - name: Static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: Docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-poistot
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:
  - name: Publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: wL6I6LfqUMbMM9F3+c+d/9lsNQVCqywsHeckrMWQ76ckUoj/k4VX8FJ0XdlctGKBX1Q=
---
kind: secret
name: docker_password
data: tCFQkhg3rtUWux0ApxB4UC1CARolEafxKPjjQ/pAkLv3TK7O1ZGV4JNgptNazQcsEFttZK2yGSCowNCJvcCDCcRxC1CgmvuJNC5Bty/9QXyg26UwITMJ8OPPDKM=
---
kind: secret
name: ssh_key
data: xagl+Ww3FolWm6vvpUjxUHEdePrslh7SD7PpLLUBxzpvLNQ9haPd8KqYtHCMZOJlDBlYoSanySphHmhyu0aNhHBWJXHL1ZzuCBtegp9q6K8BoSRshl5LExQcrLUYYDqFOFFfsQdnTLKwGpBw2wsgMnfPJKZnOE2h9P2um/8yu/gaP0q+pryysWhfbxIXBhuj2ZJVInLrmfWezwc4I5QU69DpilhqmuBxedtWW7g61SVBEcfkPxRlfg6bs8No9qWKV5J+mM/AlQm3bYBq60LojtW37Ra1AIgmmFuvMxWxow2EPpLl57RF+UxXV82pV/eYWyqfXPrBYtUgqVgN17CnyH+LKLedKwAynNbctGs63wgLyeSrwXsd1B2mglPEp0SMtlVRY1V9NCvv71vI56ID+netoJu82DHS41c7ueTTkKnkLNaCNOEOz/jrU9zhIgxDL2zAYjWSrYSVk1unKtoUoIMvKRnShIpA42/W/cslY56hV4HOT9gOynwZTkEpnzqeulg4CGjcdzRqaA9dd9ubeMs33Ay7KPsHb9soTJaNc2FNc4u7AzxWznUmmfRRGJv7voKGKrINSb84aA98CSXTmqu2l/AG35BYB254Xll1TKMANjbNDmPkATQTxb6dfoRYsb3LJkSiPRsyavSBOHBio1sMy913sPHgXMqC1XoCY8a/alyS0z8zzyD85EUmZH/+qhpMAUGBhCOdlhfw1/3jW6G84eCGLN8+4yOZxq/xd7yM10xEpLPDlFAXY+5IZfiwu3dYFotf3tnmjdvlQ9P6cuFQK/cfFBsRwF6sgfBfg3DZAk5pEygoTLfo2IdNHTLvncwc/exencKgeMUtNYYaODHhNkPunVIQL0Bej4w9n9v7NdOIJPVl9BFCZSFq3O96h9HvYBZoj3b4DahSZmq1s2WFlHPQHlr8ihV6CWYjV5wQBXKzdwTxyDpfTkWJvCkS4pgA2X5CbuzN4dlKGjK6U1yJBpF8FMYYx7Z5HwgYsKDlzI+KoYQ23m7Ljz+uSKKUTCaEN8wGejIO4b3ldJwxfGTg0Wg/4ZEvFb5igP9/Nd8lrQ02iM4t7sYU4nCgO3WL0an1BBvoVVGH2VUBQ3npuNQ10sdTKWbgSf1Z71htFDemKIOLIA4ls7xClf/27/fEQb9h0ca99lldIA/UzByPZPCyEAVz8+kgqIPxKmml4fjRBaOv38xBQhFp7vY+tQfmSnJ5HsA1ngpMlfiwT8B/qZCX6g/eLQW+E9ArzlNY/YfbMbfjykFaiUscww6e21igDrBFqUzc80XDqDpGezJygbvTJ40rHdgcIS0KdPsNC2zYgJyHjtKr94ov9B65lZ6EGf7f9T8PLY/zwTfx7qSJhWy34mWPEMtKUGSiKqX+/GbUTqK89LV7zJZDWP0L0+8/OW0SkahnCZm0lRS4lw9H44Pz4fwNt9ifolES3f29cn0x60qPmTHGpITZomcWQUqeUvX/FtdBBL7/vRI4AwnLBgpL/bQoschN1oMyZwwVM49Pp2yi2DVJibp2AmfYTtT1PILW7RW5H2aW7JsrQwEl/ruJderGLUYMw521RxODMyDVraRKQOcxfEEscv11OXSd0cudeBmd8i9M9eYoWtG5AIbDAMRRhF2vb6nVJfNU33UHYGWn7H+V1UNo0ORKzQtJZnbiLETEgQoMHGqwwlpjpnsJddgGku/kubeOlIw2Rv74UaPamc9U/uqqgGVIGzq42gQ6iK6zOTKlRjCXbi2og2uRN8YEGfGXGJNI0YlnkqCozj/u4liLEmcEKEK7ykovVT3Gj1OXXOGg9d+i5+ll/YxrPXh2jy2/YAugSMDH/Nr7X3wfJtBc8IPi906nmJD7AA7eooE9aYKLmw5OGHFe73rWhrxI8EcJxuYfiF9UneEVgHap8Rf6zFr4+KPEDGwPrv7dapsOhji61ZyRNykRtAxPzA/v8lQg5j0eboIxCIg0sBn/+sUHes3UqF024PaeFZR1bGM5kU81QuFKUo+lgpUkFdm7PzdDjgE0Ev7lcUjV6BEGzBhpOqW8zklbSdqY9x5j6Hf9W1tzn088S6kzfG2a/aRqYc99vQl7IXlyhLf10NX7/pV+tyMxx8Fg/pz/FnCceSa2A06YIvoT+PaZcPS4edGIarnL7BGPy8qjQ7iubN4EiDCIC3qK9Veii2bqK234OlxYfoTuTKQ8MRWbjPPzBuPECSgk1kvHYCAOLtSfc/WsDYilxMe8Upr/SIWEJPnDs6ZNZkWnIhRQm3Y31h7rvsNM1H7J5TSite+sd/q6ajQhj1/tzxMA2txvNZjU5cVPUzO6L/HVsvM/vnYnz78Ido2qZAswOlhd8maibmVb1m1lFsVwmiT+asiRk6UYFZHvpZmG0XU7KlyYwrgW8w4FD5cyvYh685c+MCOerzYdPjp3pf/TmiPFA2STQhAm9z3h+FVz1LGeV3DR16Bi5CL28NiZT5GvbW8w7CHG0IoMnCmKX0H0G8OgV7rjVJsTcRX9bm0dSCGbCi+7o6uO8XSoKq0n0oPS8lwps27dYnbC2G7paFkDaizFtj9muvWad+3GzZ6gKSx8j6E1wfiUSrXfUpL0ypEVLjkzKcNXE2ZbPbtsBAZtbQ0hrar3RQtECPJHvSK3Jg1bwf5yPQZtcNH4jF1EoUHS5ID6ZeiOyf3lMu5hwujDVBoYr/8wte3yzdxHh+V9eCNL3PJHHe5FtW0zXtTgzFwJMJiiAdHlNMZXtNqM0TgwSZGYTJPUJkTA3bYSaZRFMuTdfKOKiyVApmdi4Veh0XW97WJ6NIk5JteyM0O8lCidZuFpEUJr6HXXcKmRFrwLc7vyUzDRXMbhTtdcAOJsgzVkKDKY6FB84+lI3leu4DBzOXtNhFmV9bh15a2vaRNqU7nhj4gVdSZdMiXhPgVdb848NJYttzHpKmQc/icIvhrztlx/OO04SYTRZvv+rI4Mbq1rmaOa1n9oHLohztLRLKIj6Z2JrOMdiilP4XuM7fm+tny7W1tTTeILvszMni7pl7tzBCM1
---
kind: secret
name: gpg_key
data: oQ0yjgvY5qekCsS8cj0Y0vmGsL1uy7hUfkvsO5qDEj/quCYeJeJMRJQcYOTcJhmmeLBXGYNnNKBQSaLyzsScYSx4u3oHAJtOMBCtNXZxZYPJyT3BFzFePosxOAgYD3AihFdcZd5w4FxuOjcRgoKmpBgrcwLZwyMzl4Zp3kTFLoBTdu30VO8i33ScI10obksXpTrUmnDlgqLDaq6BiE2OH3i/98vFMqvscxbNTcrPFxP/RHsFNKBHtm+h+rXfJ466TrXJff7yAUuJlOcz7aDjkNYGTl4pEMNr/aj6+7dfEUyRnw4DisI/InCtJOtVlYqZ8aq6hYqymnfEKf3Jqohy35ZytgUVbcEuPPJHSSUAti0MrdL+p2+WPSWfnTIwXZ6TOzoCj0MD0i526H+CPBZ0SX4lWvx2EaoLr3yLI2Q3nltAR/ncR1TOdY30uqLTgDm1FJA8WMvZ3YEMRRviVJkxN+4cYIjxrZLJRI4+AmWxpeJpyGyFg3GA5ydrHOnRyRE+EXhJh21mJOVa6jLJ4upBv4WTjsCg/sa772r53P1gWKUdLKAeteq5bGhjkICqtT4SaftQkjPmeoHOhYd7chYkCyA+qJK4sMS674J7B98SL6sHsFD1x8Ee9wmU/VjM3M2dmVGMwlk0lDt6JZmO+nKfu+BNxC8SjaD4lr+9CDGRwNrmjmhWC+qBs9LGRvgWj73P7QuhIMwp8Qa4Ndv+PkPAtCNvQtdgAaTI4A5jkqHxVnTDIwhTO7tuf6K6l+DZ2VnFOxhIn4+ryBfn5gCsgugoD2aBDMik9rqdKtmfagRoVFwc5ENbs8cQg36A+05aqxXnmYhGsgDZXCP/glpY89OyFhuhls0cY91gKx/ahBrfOBhu7evtc1SxuvAVMEYexcUbmL8EBWkVTSAPbNp64+Ds3TA01R9Jd26hAVEAcPct5jacOC4yiX6ijC/WeFDuVUfmEcrT7IO/B9CSN3jANM+tImW+Ggec2FtbG4TjVZY1jct902f0NbqwCEwCTEqQ0eI9VJGAucNrEJZospKfsBUuhyAJOEgrCroD10UjjjxVh3ILt2LJnD/DqrcLEBX/27bbvQJuaUHpx6NwhVphSCyFOAtYcsbX3nDnzSe+SLPt61qIjp4m1A3DR3sISCDgE6VcBlOGd3FDBMLN6SL8IXOoaba0wGvn20fBPmnAwBNywnTjYwwBvvKRJY5mRdgDrrllqgWZL5gNXITXGVGqMtWQi9MfEPPlMCe/DxHNUEIiETHByTKQ4IWqjNny090t8ePHC0ZhImDs0Qk7oApDQoGz6u9+oHk0WBerO0G+Gai3YI6v10lxsEEo9jlJfHAVs5Wt1cuzLdCP78hGvsl51/ZHIusz205Bby1RlYWxFf2I/iNW2qVd1+VwHm3oN0O2CKy4Mgl0OOOh5x6qKmuiwVFWywLItwQEAlcyqD3bQRlFA03CpyDTKz0eG527IGeFBNHTqlt4M4u1TkIfcHKFfnLaeQoD+tJf4cDyZckCsRgk67itp1qlzi1H51vz7c0taxGTJd2SSOMDvhZvxIvmwMnYYgruzoimgQdvyYHeLtVZORfSQAe72GPylyPcxB0NOHWHdy2NHdgeB6cyuSReIyYW60fgw0NfXvzhTwGMe3eenkmuNvP1nxR3kC6pSK5/m/6+iT4gk8dnH0GJCVnNztsBxVCXPBOaLRaeUFPGbsB7aC2307gKWnpmdt+kyiSCWvKAjjMdmrFBwttEf86jN3Xv1t5GsCdWTHSl4qNGAPV9S1BFtV/bvx0rRXDEsTEBkeQ0FeN7orf/K9H3DlOCu2athgK80qm8T2xkeDaWeO8OabEAB4cBWxL1EILwjq2dyg5NsvqUU2LxbUBQasOBr4uznLAntghSGfHo8E2gR9CWMyxy1vRIC3Vn+k9sbp/COlQKUta8xugx/2dQP3rX7Zafed4/bmRd5D4UzUZlcaCMTDMrpE484Ok8Di22DixXa7JGL5b9a/Ht5tw4O6JZ0z+Q0f29LF+mGRJVb2dYMDJ0I3vS4nANFtrRBf4rg/HRxIu02IVt1NmxQAqqu/jietcVPcit171LiMqZwHWpUSkR3lmYkaCFCY+V6vVbiy4+QuOtbBc48TnIA+gq2CZioPNv5vqkQV8letsCW80ekQJOh8BAsnuvXks1Va/koPIXuInU9VD9Qs6jLzClsIa66gyg4piVcRWy8r6S5LYjBQiWAPukbJAaALlfg0Ra1cVrfLAfccadd5BZ2JNrvxQfsp+bUxVU/VqjdrD00lAGUu6ga+z96W8mTxaQwKijLHnyLQ0gvCu+x5GoepLikaXNIEln160IBJu16AzlzDmMADk/E4o37lzRDuWBI5ichzXJhck3+YD5eQkVG7N+TA4qVDO0OijSZUFenamqQA0bjIeTg1OsADH8+3apFC2eBADLg62Q0034OrzdaVxp8mmYQvWZZYHTrT3EaDz2H4RFBj+ivR/zSyBPlf3NPLbWdUo/YbTBy72/N0X81hpHLHI67FBtkIqesUTyKa1kZ1GQgC9ppqrc/7fFuC/hBfGBmANtxAvHaRQp+19YiJHr1GQc6tsEhY7u2jKzKZaMUhl0ytvI8beQYkn7EVQ45KI7SabBFCQ1l8qwUeXMlxIgSE1T/WIAUNYx9sTLIGIv0X6wdTauC1skfwYtnnZ/pKjyz9iRa1mgCZbatRl18V1DyiNA4ebrA3eJ2DMn/IjI4WOXwkQtUnnHxDVPVlcFSXJS0f1ivlG1CyW1cfizEfsNvHY8N3KKToUa7hNGSuT8pYktaN1v2T5Rvj/DZBwhG9VKmf5urE+dHmMvL7C07MWSCccevtuanJoI3Ezc54rTjWdvuKgd+dvZ9inl/4UQopPnCtuaFQA/T6Z/Az+OlW1tp6gT9MUl+fpKD70kFs9bFS2tQqX+X9CKmY99GV0wKKBJWZ3JjuFi9whRg7/7O1Nly7wVaSKy2p4K8HTYAgc18F2IOPIIGVENvD4ngYjYy7xq5LwnHIZHlCtZSyi6iE/jswRelmhivoAvwyq7rlnYPNMbjDvS68EN+YCdC+UcRJ9ai33FvpRAQnhvrox984lvsrfpYPDgsdPMZ8FERLgB14+i1euNiDS6vefaOKH6jmqxNq1kvrr8Rzwgh3w7B5VN8bkn7u3zDKarguRFZwgYjb6312E1rNkgpB2qTumH49ZrbpOxQqBHGBYNQCmwwa9I7NM8obNsU427NycT6GkhUBLNHmKmbEmQ8qru9TGS+Cbbr9tP0nvRSnAOMvqUN3U2lpjT7NK60bYBkhZcBGbVdc0NFWrafFQQBZUiXhNZzKJHJs1CeiC0SaizJ5UHkNp3ByEKGgrxrSZPPBlrkuM4/cql24TsBn2nMz4RaFwf/tymPP7L1g+al8X6nJWiYSHlk0YfVRp8YZSPE5g90ZvDonnPZlrXY9pOzzy1SKlMlnpKzl11Mkp4OdewYlMdnTd2T9/rVUWOwISa7XeOF2rzMqEKSvk/cpt9VTNbeyraQ1s4v29vuQ2LLkVJMX/ZbwecbDOb+F+HVCcF9JuYCCqNhQ0Z8nD1OVk7Kh/gpHvslrLbgJkdbLTCfPTHXElA3NQ0eNptLjAxMKWsXyq8DMhOCOueGiaVqGmDNr381BVRdk2x7IfpsfhLVASjzyOlUve52huJ6NHNgdmdGLJWEGwVtgckpW8viKT0dKWHMe4814bHiAK8oIaqJQvDwZWUlbGfg88JVi85HzWBK41o65cgsIxUUYqccYmLozt4IZrmMNtz5T/QaWdFw0GFTySIyNYDmhgPPlQdQuom9a5TNpTL9NxA9Rx619wNJO9f6zT+k/ms5xJgjoG+eBD+J98flr+LnUpiJFP/t1DAGLeGSjXGmJ6QGPep5jMqfnuAS7BeWsRogtg5Rs+U4+BL3QZ5DCkk6J1x6WC3K2AN3W2a6EfmaUs+FgEArrWfNxux/tj+TdmMcUpEL4ZNT31vYAiJu6OuHaHWLMtm6WP9VjTJ5UHpvj/ajO8Cr6D24R9sF5gHx0F8Z/9nbxyWftlz2yZlcMhInqaZ4Frz3+2RWJ4RD+Q+TeqRElH8KDclhE0HlEwe5PHtdW2DHTrL0AukJVnXX2Qpujr2hnU/2LesuksFdCsvl8kNp3PuUPDJo74mLtA9n3pQNvbk5ZY75lKq2de5jFqEwdUqcAEjkEOay9E6GJUsRGXCNylbCpTU2Sx0EOMt8HZkqppyb5hNk0ctKNGJbA5Mc0UtfEaWIB9pYugWs9zWKafZwV/8tGIRCSyzUn9s3/89LMyMgiTiF703I29Gyt8e9xFTMhLOQoNmdidPxxtx9WxRY3YvDaiPRip701DeRmKmIPfpaR91/v4alA111Kq+BVnsK8eM3qBZkCLrxXOGPFoncUZKlq9sqSg8XpH+V5KBvyM+APAlGuh/zoV8c4EAQaoOP8I9fIIHk37W1TF1MEBxqJP6AQ2GybD4BjJB5KNxrqXiLrUew5u9GvN/vYGUvhlYVRO4vtBG6h2Em+rDf9UwTrvLjo/L1B+wxJPlaew1yszUrLd+NGxZNY4ngYhv8R9Li1frNtQQJMZPAnvuxUSvbJ8QreHeXhV/IJ/gLJZSUieUMc8wcNn/+Mguwr39sLeA9fT1ENqmaFjOqrZSu0ci3T5GZhbcZQBdrUqZncMX3UgA3WtThFqv5T7R8s3tl3xOUFlMRw7iWosNRywyvMR1zxaW/Nj3K/sqG3aPE5j1VYMfs29HTxxW8NyJqGG5SeQVL3ZwEwkULIJviftXVif8rY8g4wPyxq56GCVTgIRY0RQXU3hLCblA8/b5x2Emji9tdH1sNsdUcm8bqjVSNsCwlxmkNgwH2chTf2X6DVcQYBnhD5sRpGcEkePIEkLXFlsNdMpXujeTv6r4sr0YKoiXW3fyPLqbGUu4lobR8Trryga6KYDm/+Es4yMMNlhKk4uHeXWBx0Yu6AAD7prFVQDLSMKMFi2KYlfoFl+nA+8hzI51p0Dx3JrtfX+Pq8rc0zu8n6IVogtQXy2YClCaPttgFXiQkcT5OwZjC79TWBRqMJIlt6AdHiXhbwb9p64ttuuPBcrn3n9exkdXpitSJss6Lsj1I5ZxCChKYEgRqvlnCmOVB7sTs7+B7S3UZSS9xU0qaI/AitMhTpstUQWqkLCkc9fNM/tOat35SqPPnbzf6VMxRfV3k2Gxq1RjXBV2a8GttzyagWjlOuJEKUVOTJJSUaixe8R7UghcD8Oo86jz5p6ti9t2VDf7eWu1kaPP+T0RZzuhuHtXMtev2XaEKbimGddE79ZOxbC8lzxmNa7wAbO6K5w4/0ysUaEXOjIQ6lt+Cv++8lwct10nU1E3x4Edk/wTcYONqr+tMrw+B2/NhzeIW2HwfAhXcl75QZ32KPMWfD+Vb0qfZRKK9kzuX+khxohguFbbQYnvbTYaz19xPi5+xLDtgpo8b2VZ8PwFSVTV/91EeAharLW3r4Ru4PF4C2JT0S/CnOU1dYGHLMt8vTH29g4gpi6QoBqGeWaGmJ0uj5uA9qbzV9aku1Xa2hX6N1LRJz+zpjgyz/Xc5cgmBew1kEEFl0FAI6NLKU2k0ONQEugJk0YEyjjjSoZUwx0VbKNSO9uEwe/fbHecVteK4ardZMkC80rb/spjb5R3JZJ4YjW/IuRPku+nVFytp7e+Lqsz26u5U4CpUV5hpXRl55j4mlpCEbBCqFhxcVr0vIzNDtbNRLm4QNOrM/sSr++Cd1jmFNpn8CiLpZvbnR8yNA82Gjc1EQmAldvesoH2Ntaui4ymmTiW6Ha6IL7KYTg22y/WjfpRcXBnXJV+P6M2IDdoCrp6kSq1przAONgDxMIC4GioQ+r/Ue3fbBvrgVfmsIVTqOea8LGByCSgPoRL+lRJv2vj/4N8BNVqAxOUnV75l8bLQrY9D5To7D7ZgXOyOQHgsjiKcizyDhfyzU2sWh/0AO7z+nSkzFcZsEBEwvjNUqjEbx9DaADDjvLIfxHpLXKUP0GTU5ZPIjouaplnpK5cAlB8BN1ZIbAcaYnbUKxuvXUJzfayTG7FDy862Hza32M/AkR80d1iqhwnZ71jn7pxVtS0wx0e9WDGsxm9+AUG6S75EYIgwv7Z/hU+A1upjhcy6UyPTtA2R3N5NTkUaptCnB/vuU/iU/NeFxM85OhApSHN9mnlsY1yhKFwV/eX/7zrFNk7rrJNseR9LYPDkQ/bPafMWW2rWXvekL2zslx/SnQaUfB42xp75UZp0Zridgb+WWx7tROKaqQab2fR20LTom7CYMBaiVb/Fn9fYJzYUFnNdvbzedBHO6SpNs4YYESCCWmd3H7zdwBvlAFXEEEw90NZIZqZ+tZyxR5xBajKCJKC4nQvG74h8oR39Rk7BahHDrSkPYnFN0uKAgWy/4hdFMYXDYpwaTzT5L5InnqSXhLPcOr7NyWP7b4Qf36wdqrA8H6wzhyEkZrglOAdlFU/vEwzK+L70tKf/cob/DkKw1z9z9JRFPuDpJ1hPQPLKy2apuC80K/2UuHKeP8Km022AujkC4LbBAHUjOLsLPQF4d8eI9hQDNE4jpOO2RAHsucWJVDn5emQJnDa4PMO3rErxalzbr6gHpbAarG9PJRhsml46HxjES8uIUnFrI/lTGsbkX559dd4MrCfnygAxRJ0m40W0/Ct0a/CJiFiDqtlrjm0/cjw/vZVIzYQ+GvTIiSbZuVhXngZvevwgg==
---
kind: signature
hmac: 528e37d0a7b835904ac5b8bb87418543068b906bf91c1c3274c054a6f1a9cfca

...
